- name: Demo on AWS SSM Parameter pull
  hosts: localhost
  tasks:
    - name: lookup ssm parameter store in the current region
      debug: msg="{{ lookup('amazon.aws.aws_ssm', 'sample',region='us-east-1' ) }}"