- name: Demo on Error handling
  hosts: localhost
  tasks:
    - name: Same shell command
      ansible.builtin.shell: lss
      ignore_errors: yes

    - name: Print Hello
      ansible.builtin.debug:
        msg: Hello


