- name: Expense Frontend Setup
  hosts: all
  become: yes
  tasks:
    name: Installing Nginx
    ansible.builtin.dnf:
     name: Nginx
     state: present
- name: Copy Expense Config File
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf
